language: java
sudo: false
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6

install: true
  
cache: 
 directories: 
 - '$HOME/.m2' 
 - '$HOME/.sonar/cache'
  
branches:
  only:
  - develop
before_script: ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: ./mvnw test -B