language: java
sudo: false
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6

install: true
  
env:
  - MAVEN_VERSION=3.2.5
  
cache: 
 directories: 
 - '$HOME/.m2' 
 - '$HOME/.sonar/cache'
  
branches:
  only:
  - develop
script: ./mvnw test -B