language: java
sudo: false
jdk: oraclejdk8

install: true

script: 
 - "mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install"

cache: 
 directories: 
 - '$HOME/.m2' 

branches:
 only:
 - developer
